env_args:
    env_name: pong_v1
    env_type: pettingzoo
    num_envs: 1
    ram: True
    seed: 12234

agent_args:
    hidden_dim: 64
    algorithm: DQN
    algorithm_spec:
        dueling: True
        replay_buffer_size: 1e5
        gamma: 0.99
        multi_step: 1

train_args:
    batch_size: 64
    max_episodes: 10000
    max_steps_per_episode: 10000
    optimizer: adam
    learning_rate: 1e-4
    device: gpu

