env_args:
    env_name: pong_v1
    env_type: pettingzoo
    num_envs: 1
    ram: True
    seed: 12234

agent_args:
    hidden_dim: 64
    algorithm: DQN
    algorithm_spec:
        dueling: True

train_args:
    batch_size: 64
    max_episodes: 10000
    max_steps_per_episode: 10000
