env_args:
    env_name: SlimeVolley-v0
    env_type: slimevolley
    num_envs: 1
    against_baseline: False
    ram: True
    seed: 1122

agent_args:
    algorithm: GA
    algorithm_spec:
        num_agents: 500
        mutation_power: 0.2  #hyper-parameter, set from https://arxiv.org/pdf/1712.06567.pdf
        max_generations: 500000

train_args:
    max_steps_per_episode: 10000
    optimizer: adam
    learning_rate: 1e-4
    device: gpu
    update_itr: 1  # iterations of updates per frame, 0~inf; <1 means several steps are skipped per update
    log_avg_window: 20 # average window length in logging
    log_interval: 20  # log print interval 
    render: False
    net_architecture: 
        hidden_dim_list: [128, 128]  
        hidden_activation: ReLU
        output_activation: Softmax

    # test: True
    # load_model_idx: 20210707185814/9541

    marl_method: selfplay
    marl_spec:  # configurations for specific MARL method
        {}